name: Snakemake Dry Run

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10

      - name: Install Snakemake
        run: conda install -c conda-forge -c bioconda snakemake

      - name: Run Snakemake dry-run test
        run: |
          snakemake --cores 10 --use-conda --dry-run --config \
            processing_dir="tests/test_counts/test_out/processing" \
            results_dir="tests/test_counts/test_out/results" \
            benchmark_dir="tests/test_counts/test_out/benchmarks" \
            genome_index="tests/test_counts/genome/random_genome" \
            gtf_file="tests/test_counts/genome/annotation.gtf" \
            samples_csv="test_samples_counts.csv" \
            cleanup_processing='True'
